config/routes.rb
Rails.application.routes.draw do
  resources :loans
  resources :books
  devise_for :users, :path_prefix => 'my'
  resources :users
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  	@about_me = "My Name is John Elder..."
  	@answer = 2 + 2


  	

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #0d918c;">
<a class="navbar-brand" href="/">
  <%= image_tag( root_url + "i210.png", size: "60x60", :alt => root_path ) -%>
  <%= link_to 'Biblioteca - ISFDyT Nº 210'.html_safe, root_path, class:"navbar-brand" %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
    <% if can? :read, :all %>
        <li class="nav-item">
        <%= link_to "Libros", books_path, class:"nav-link" %>
        </li>
    <%end%>

      <% if current_user.present? %>
        <li class="nav-item">
        <%= link_to "Prestamos", loans_path, class:"nav-link" %>
        </li>
        
      <%end%>

      

      <% if can? :manage, @user %>
        <li class="nav-item">
          <%= link_to "Editar Perfil", edit_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Agregar libro", new_book_path, class:"nav-link" %>
        </li>
      <% end %>

      <li class="nav-item">
        <%= link_to "Contacto", home_about_path, class:"nav-link" %>
      </li>

      
      <% if can? :manage, @user %>
      <li class="nav-item">
      <%= link_to "Registrar Usuario", new_user_path, class:"nav-link" %>
      </li>
      
      <li class="nav-item">
      <%= link_to "Usuarios", users_path , class:"nav-link"%>
      </li>
      <%end%>
      
      <% if current_user.present? %>
        <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      <% end %>

      <% unless current_user.present? %>
        <li class="nav-item">
          <%= link_to "Loguearse", new_user_session_path, class:"nav-link" %>
        </li>
      <%end%>
    </ul>
    <% if user_signed_in? %>
    <p style="color:white; font-size: 1em">Email: <%= current_user.email if current_user %>
    <br>Rol: <%= current_user.role if current_user  %></p>
  <%end%>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Contacto</h1>

<a href="https://isfdyt210-bue.infd.edu.ar/sitio/">Pagina Web del Instituto</a>

app/views/home/index.html.erb
<h1>Hello World!</h1>
This is my first Rails Webpage...