config/routes.rb
Rails.application.routes.draw do
  resources :loans
  resources :books
  devise_for :users, :path_prefix => 'my'
  resources :users
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/loan.rb
class Loan < ApplicationRecord
    belongs_to :book
    belongs_to :user

    validates_associated :user

    validates :user_id, :book_id, :loan_start, :status, presence: true

    before_validation do
        self.loan_start = Date.today if loan_start.blank?
		end

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
    @books = Book.all
    @users = User.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
    @users_availables = User.all.select { |user| user.valid_amount_of_loans? }
    @books_availables = Book.all.select { |book| book.loans? }
    @status_student = 'Reservado'
    @status_librarian = ['Reservado','Entregado']

    @book_list = @books_availables.map { |book| [book.full_title_id, book.id] }
    if @book_list.empty?
      redirect_to root_path, notice: 'No hay libros disponibles'
    else
      @user_edit_list = @users_availables.map { |user| [user.email, user.id] }
    end
  end

  # GET /loans/1/edit
  def edit
    @status_librarian = ['Reservado','Entregado','Cancelado','Finalizado']
    @users_availables = User.all.select { |user| user.valid_amount_of_loans? }
    @user_list = @users_availables.map { |user| [user.email, user.id] }
    @user_loan = Loan.find(params[:id])
    if @user_list.include? @user_loan
      @user_edit_list = @users_availables.map { |user| [user.email, user.id] }
    else
      @user_edit_list = @user_list.unshift([@user_loan.user.email, @user_loan.user_id]).uniq
    end
    @books_availables = Book.all.select { |book| book.loans? }
    @book_list = @books_availables.map { |book| [book.title, book.id] }
    @book_loan = Loan.find(params[:id])
    @book_edit_list = @book_list.unshift([@book_loan.book.title, @book_loan.book_id])
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loan_params
      params.require(:loan).permit(:user_id, :book_id, :loan_start, :loan_end, :status, :gave_loan, :received_loan)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
    def user_email(loan)
        loan.user.email
    end

    def book_title(loan)
        loan.book.title
    end

    def corrige_fecha(fecha)
        if fecha.nil?
            ''
        else
            fecha.strftime("%d-%m-%Y")               
        end
    end

    def limit_date(fecha)
        if fecha.nil?
            ''
        else
            (fecha+15).strftime("%d-%m-%Y")               
        end
    end

    def limit_date(fecha)
        if fecha.nil?
            ''
        else
            (fecha+15).strftime("%d-%m-%Y")               
        end
    end

    
end

app/views/loans/_form.html.erb
<%= form_with(model: loan, local: true) do |form| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
        <% loan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <% if can? :manage, @loan %>
    <%= form.select :user_id, options_for_select(@user_edit_list), {}, class: "form-control" %>
  <% else %>
    <%= form.text_field :user_id, class:"form-control", placeholder:"#{current_user.email}", value:"#{current_user.id}" %>     
  <% end %>
  </div>
 
  <div class="form-group">
      <%= form.select :book_id, options_for_select(@book_list), {}, class: "form-control" %>
  </div>
 
  <div class="field form-group">
    <%= form.date_field :loan_start, class:"form-control", placeholder:"Fecha de Inicio" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :gave_loan, class:"form-control", placeholder:"Entrego Prestamo" %>
  </div>

  <div class="field form-group">
    <%= form.date_field :loan_end, class:"form-control", placeholder:"Fecha de Finalizacion" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :received_loan, class:"form-control", placeholder:"Recibio Prestamo" %>
  </div>

  
  <div class="form-group">

    <% if can? :manage, @loan %>
      <%= form.select :status, options_for_select(@status_librarian), {}, class: "form-control" %>
    <% else %>
      <%= form.select :status, options_for_select([@status_student]), {}, class: "form-control" %>
    <% end %>

  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
  <br>

<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<h1>Prestamos</h1>

<br>
<table class="table table-striped table-bordered table-hover">
<thead class="thead-dark">
<tr>
<th>ID</th>
<th>Usuario</th>
<th>Libro</th>
<th>Fecha de Inicio<br>Entrego Prestamo</th>
<th>Fecha de Recepcion<br>Recibio Prestamo</th>
<th>Fecha Limite</th>
<th>Estado</th>
<% if can? :manage, @loan %>
  <th></th>
  <th></th>
<% end %>
</tr>
</thead>
<tbody>
<% @loans.each do |loan| %>
  <tr>
    <td><%= link_to loan.id, loan %></td>
    <td><%= user_email(loan) %></td>
    <td><%= link_to book_title(loan), book_path(loan.book_id) %></td>
    <td><%= corrige_fecha(loan.loan_start) %><br><%= loan.gave_loan %></td>
    <td><%= corrige_fecha(loan.loan_end) %><br> <%= loan.received_loan %></td>
    <td><%= limit_date(loan.loan_start) %></td>
    <td><%= loan.status %></td>
    <% if can? :manage, @loan %>
      <td><%= link_to 'Editar', edit_loan_path(loan) %></td>
      <td><%= link_to 'Borrar', loan, method: :delete, data: { confirm: 'Estas Seguro?' } %></td>
    <% end %>
  </tr>
<% end %>
</tbody>
</table>


<%= link_to 'Nuevo Prestamo', new_loan_path %>

app/views/loans/new.html.erb
<h1>Nuevo Prestamo</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Volver', loans_path %>

app/views/loans/show.html.erb
<div class="jumbotron">
  <h3 class="display-6">
    Estado del Prestamo: <%= @loan.status %><br>
  </h3>
  <h3 class="display-6">
  Libro: <%= @loan.book.title %>
  <br>
  Retiro Usuario: <%= @loan.user.email %><br>
  </h3>
  <p class="lead">
    Entregado en: <%= @loan.loan_start %><br>
    Entregado por: <%= @loan.gave_loan %><br>
  </p>
  <p class="lead">
    Finalizado en: <%= @loan.loan_end %><br>
    Recibido por: <%= @loan.received_loan %><br>
  </p>
  <br/>

<% if can? :manage, @loan %>  
<%= link_to 'Editar', edit_loan_path(@loan), class:"btn btn-secondary" %>

<%= link_to 'Borrar', @loan, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
<% end %>   
<%= link_to 'Volver', loans_path, class:"btn btn-dark" %>

</div>